AWSTemplateFormatVersion: "2010-09-09"
Description: Knowhere EC2 Stack CFT

Parameters:
  S3BucketPath:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/gamehost/s3bucket/path'
  S3BucketArn:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/gamehost/s3bucket/arn'

Resources:
  # TODO: add API Gateway + Lambdas
  