name: Jump Point API deployment
on:
  push:
    branches: [ "develop", "main" ] 
  pull_request:
    branches: [ "feature/*", "bugfix/*" ] 
  workflow_dispatch:
permissions:
      id-token: write
      contents: read
jobs:
  checkout_code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          role-session-name: githubactions
          aws-region: ${{ secrets.AWS_REGION }}
  
  build_app:
    needs: checkout_code
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
      - name: Install dependencies - LGSM Send Command
        run: npm ci
        working-directory: src/lgsm-send-command
      - name: Build app - LGSM Send Command
        run: npm run build --if-present
        working-directory: src/lgsm-send-command
      - name: Build SAM environment
        run: sam build --use-container
  
  #test_app:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Run unit tests
  #      run: npm test
  
  deploy_app:
    needs: build_app
    runs-on: ubuntu-latest
    steps:
      - name: Deploy code
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
          