name: Jump Point API deployment
on:
  push:
    branches: [ "develop", "main" ] 
  pull_request:
    branches: [ "feature/*", "bugfix/*" ] 
  workflow_dispatch:
permissions:
      id-token: write
      contents: read
jobs:
  checkout_code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          role-session-name: githubactions
          aws-region: ${{ secrets.AWS_REGION }}
  
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
      - name: Install dependencies
        run: npm ci
      - name: Build app
        run: npm run build --if-present
      - name: Run unit tests
        run: npm test
      
  
  deploy_aws_cloudformation:
    runs-on: ubuntu-latest
    steps:
      - name: upload cft to s3
        run: |
          aws s3 cp ./jumppoint-api-cft.yaml "${{ secrets.AWS_S3_PATH }}/jumppoint-api-${branch}-cft.yaml"
      - name: deploy to aws cloudformation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: "jumppoint-api-${branch}"
          capabilities: CAPABILITY_NAMED_IAM
          template: "${{ secrets.AWS_S3_URL }}/jumppoint-api-${branch}-cft.yaml"
          parameter-overrides: >-
            Branch="${branch}"
      
      - name: delete failed stack
        if: failure()
        run: |
          aws cloudformation delete-stack --stack-name "jumppoint-api-${branch}"
          